name: Publish Images
on:
  push:
    tags:
      - '**'
jobs:
  publish-devcontainer-image:
    if: startsWith(github.ref_name, 'devcontainer')
    name: Push Devcontainer Image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3
      - name: Split Tag and Save to Action Output
        id: splitTag
        run: |
          export FULL_TAG=${{ github.ref_name }}
          echo imageTag=${FULL_TAG##*/} >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push the Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./devcontainer
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/devcontainer:latest, ghcr.io/${{ github.repository }}/devcontainer:${{ steps.splitTag.outputs.imageTag }}
